language: generic

sudo: required
services:
        - docker

before_install:
        - docker build -t syckercoder/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true benfsmith3/docker-react npm run test
